### ISSUE TITLE
ERROR in ./.uizoo-app/index.js

### ISSUE THREAD

**Issue by canadianeagle** [myheritage/UiZoo.js#79]
Hello,

First of all, loving the demo of UIZoo I saw - I look forward to using it.

However, I can't. I've tried installing it an existing project and a brand new project, both bootstrapped with Create React App; both don't work with the following error:

Command I ran: **uizoo**

**Result**
(node:55924) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    +*+*+ UiZoo up on localhost:5005 +*+*+
× ｢wdm｣: Hash: c6bdfad7b3ff31ee778b
Version: webpack 4.41.0
Time: 8222ms
Built at: 10/04/2019 10:17:32 AM
            Asset       Size  Chunks         Chunk Names
    components.js    164 KiB       0         app
components.js.map  109 bytes       0  [dev]  app
Entrypoint app = components.js components.js.map
[0] multi (webpack)-dev-server/client?http://0.0.0.0 (webpack)/hot/dev-server.js ./.uizoo-app/index.js webpack-dev-server/client?http://localhost:5005/ webpack/hot/dev-server 76 bytes {0} [built]
[./.uizoo-app/index.js] 2.67 KiB {0} [built] [failed] [1 error]

**Eventually get this error:**
ERROR in ./.uizoo-app/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In C:\Users\***\node_modules\babel-preset-react\lib\index.js
    at createDescriptor (C:\Users\***\node_modules\@babel\core\lib\config\config-descriptors.js:178:11)
    at items.map (C:\Users\***\node_modules\@babel\core\lib\config\config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (C:\Users\***\node_modules\@babel\core\lib\config\config-descriptors.js:109:29)
    at createPresetDescriptors (C:\Users\***\node_modules\@babel\core\lib\config\config-descriptors.js:101:10)
    at passPerPreset (C:\Users\***\node_modules\@babel\core\lib\config\config-descriptors.js:58:96)
    at cachedFunction (C:\Users\***\node_modules\@babel\core\lib\config\caching.js:33:19)
    at presets.presets (C:\Users\***\node_modules\@babel\core\lib\config\config-descriptors.js:29:84)
    at mergeChainOpts (C:\Users\***\node_modules\@babel\core\lib\config\config-chain.js:320:26)
    at C:\Users\***\node_modules\@babel\core\lib\config\config-chain.js:283:7
    at buildRootChain (C:\Users\***\node_modules\@babel\core\lib\config\config-chain.js:68:29)
    at loadPrivatePartialConfig (C:\Users\***\node_modules\@babel\core\lib\config\partial.js:85:55)
    at Object.loadPartialConfig (C:\Users\***\node_modules\@babel\core\lib\config\partial.js:110:18)
    at Object.<anonymous> (C:\Users\***\node_modules\babel-loader\lib\index.js:144:26)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\tonye\Dropbox\__Dev\_AWSloop\__PersonalExperiments\mapbox-test\node_modules\babel-loader\lib\index.js:3:103)
 @ multi ./.uizoo-app/index.js webpack-dev-server/client?http://localhost:5005/ webpack/hot/dev-server app[0]

**Here's my package.json**
{
  "name": "mapbox-test",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@babel/preset-react": "^7.0.0",
    "@material-ui/core": "^4.1.3",
    "babel-core": "^6.26.3",
    "deck.gl": "^7.2.6",
    "material-ui-icons": "^1.0.0-beta.36",
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-map-gl": "^5.0.11",
    "react-map-gl-geocoder": "^2.0.11",
    "react-router-dom": "^5.1.0",
    "react-scripts": "3.1.2"
  },
  "scripts": {
    "start": "set PORT=3006 && react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "uizoo": "node .uizoo-app\\webpack.uizoo.js"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "babel": {
    "presets": [
      "@babel/preset-env",
      "@babel/preset-react"
    ]
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/preset-env": "^7.6.2",
    "babel-loader": "^8.0.6",
    "babel-plugin-syntax-dynamic-import": "~6.18.0",
    "babel-plugin-transform-flow-strip-types": "~6.22.0",
    "babel-plugin-transform-object-rest-spread": "~6.26.0",
    "babel-preset-env": "~1.7.0",
    "babel-preset-react": "~6.24.1",
    "css-loader": "~3.2.0",
    "style-loader": "~1.0.0",
    "uizoo": "^1.3.0",
    "uizoo-app": "~0.1.0",
    "webpack": "^4.41.0",
    "webpack-dev-server": "~3.8.2"
  }
}

I would really appreciate any help. I can provide more information as needed.

Thanks :)

**Comment by heath-freenome** [comment]
I'm seeing pretty much the same issue with trying it out on my new component library I'm building.  It seems pretty busted... Guess I'll just use storybook

**Comment by canadianeagle** [comment]
It looks like this library is dead? No response (it's been 3 months) and no updates to the repo (2-3 years).

**Comment by liorgreenb** [comment]
Hey,
sorry for the late response.

We have decided to no longer maintain UiZoo, sorry for the inconvenience.

New message in readme:
*** DEPRECATED ***
UiZoo is currently deprecated and this repository is not actively maintained. If you are interested in this library and would like to take the responsibility of maintaining it, please send an email to lior.greenberg@myheritage.com. Thanks for supporting us, sorry for the inconvenience!
